### ISSUE TITLE
Hitting 'load older emails' in rapid succession leads to error

### ISSUE THREAD

**Issue by felixrindt** [hpi-swa-teaching/IMAPClient#180] opened 2019-05-06 10:01 UTC
Maybe it's because the endpoint is not blocked from handling two UI requests at the same time.

As a user, I'd like the app not to error if I mistakenly hit the load older mails button too quickly.

**Comment by timgarrels** [comment] 2019-07-19 12:46
This is caused by `ICFolderDialog loadOlderEmails` which uses multithreading.
I don't know why, I guess previous devs wanted the client to work while old mails are fetched in the background.

That means that every time you hit the button, a new thread is forked.

Futhermore `self selectedFolder loadOlderMails` is called in these threads which reset the selected folder.

So thread 1 might set selected folder to nil and before a new value is stored thread 2 might access that nil with `self selectedFolder loadOlderMails`.

This is a runtime condition.

I propose to remove the forking in  `ICFolderDialog loadOlderEmails`. We should check, how long it might take to fetch older mails.
We could also make sure that selectedFolder is multithread save, but this seems like an overkill

**Comment by brokkoli71** [comment] 2022-08-03 17:55
is fixed on the sync button with limiting the number of parallel syncing processes to one. Load older Emails does not have the problem currently

**Closed as completed by brokkoli71** 2022-08-03 17:55 UTC
Labels: bug
