### ISSUE TITLE
FolderDialogInstance does not have an emailAccounts object

### ISSUE THREAD

**Issue by martintaraz** [hpi-swa-teaching/IMAPClient#178] opened 2019-04-30 09:56 UTC

**Comment by timgarrels** [comment] 2019-04-30 10:01
We added an account, which worked perfectly fine. After closing all client windows and reopening the client with the command `ICLoginDialog open: ICFolderDialog new` and adding the same account again under different name, the program crashes.
 This is because the ICLoginDialog executes it's login method, and went into this line
```ifFalse: [folderDialogInstance addAccount: dataDictionary]```
and the folderDialogInstance calls `self emailAccounts add: [...]` but self emailAccounts is nil.

**Comment by felixrindt** [comment] 2019-07-25 16:13
Can reproduce an issue here, although the code path changed is different. Open the App using `ICLoginDialog open: ICFolderDialog new`. Directly add a new account.

**Comment by Veladus** [comment] 2020-07-31 09:48
Was closed by #346

**Closed as completed by Veladus** 2020-07-31 09:48 UTC
Labels: bug
