### ISSUE TITLE
ICEndpoint with SSL enabled returns SSL error -2 on closing

### ISSUE THREAD

**Issue by msoechting** [hpi-swa-teaching/IMAPClient#43] opened 2016-07-28 09:20 UTC

**Comment by krono** [comment] 2017-07-17 08:44
What OS? What version of SqueakSSL? what does Stdout say when using SqueakSSL with logLevel 1?

**Comment by timgarrels** [comment] 2019-06-25 07:57
This is 3 years old, was not reproduced yet and seemed to never occur again. I suggest to close this ticket as its highly unlikely that we can reproduce it 3 years after.
@EightSQ @martintaraz @Paulpanther @felixrindt

**Comment by timgarrels** [comment] 2019-06-26 10:48
I just reproduced this:
Open IMAP-Client, log in with a valid account (there is no need to actually fetch mails, just login), close and reopen squeak. Error

I assume this is caused because squeak saves the state and loads it up again and the open ssl connection can not handle that.

@krono
Linux 4.15.0-43-generic #46~16.04.1-Ubuntu x86_64
As I can not find a version number for SqueakSSl, here the timestamps on the last commits for
SqueakSSL-Core: 9.May 2017
SqueakSSL-SMTP: 27. November 2011
SqueakSSL-Tests: 4. January 2019

**Comment by felixrindt** [comment] 2019-07-25 15:49
Can confirm what @EatingBacon wrote. This is related to #29.

**Comment by krono** [comment] 2019-07-25 17:03
please set logLevel: to 1 SqueakSSL and report what the stdout says

**Comment by felixrindt** [comment] 2019-07-25 18:37
With `logLevel: 1`, there is no output produced on the VMs stdout when the error occurs.

**Comment by felixrindt** [comment] 2019-07-25 18:39
This is what happened before I restarted the VM:

> sqDecryptSSL: Decrypted 266 bytes
sqEncryptSSL: Encrypting 46 bytes
sqCopyBioSSL: 75 bytes pending; buffer size 4096
sqDecryptSSL: Decrypted 22 bytes
sqDecryptSSL: Decrypted 266 bytes
sqEncryptSSL: Encrypting 46 bytes
sqCopyBioSSL: 75 bytes pending; buffer size 4096
sqDecryptSSL: Decrypted 22 bytes
sqEncryptSSL: Encrypting 15 bytes
sqCopyBioSSL: 44 bytes pending; buffer size 4096
sqDecryptSSL: Decrypted 343 bytes
sqEncryptSSL: Encrypting 8 bytes
sqCopyBioSSL: 37 bytes pending; buffer size 4096
sqDecryptSSL: Decrypted 21 bytes

**Comment by felixrindt** [comment] 2019-07-25 19:04
The explanation for this issue can be found in `Socket>>primSocketConnectionStatus: socketID`

> "Return an integer reflecting the connection status of this socket. For a list of possible values, see the comment in the 'initialize' method of this class. If the primitive fails, return a status indicating that the socket handle is no longer valid, perhaps because the Squeak image was saved and restored since the socket was created. (Sockets do not survive snapshots.)"

This seems to be what happens. Solving #29 in a proper way should also solve this.

**Comment by felixrindt** [comment] 2019-07-25 19:08
The error we see is produced in `SecureSocketStream>>receiveDataInto: buffer startingAt: index`:
> [count := ssl decrypt: readBuf from: 1 to: bytesRead into: decoded originalContents.
		count < 0 ifTrue:[^self error: 'SSL error, code: ', count].

**Comment by krono** [comment] 2019-07-31 11:36
Seems this is a non-issue then.
Maybe better documentation or another error code, but I'm inclined to say "works as intended", no?

**Comment by felixrindt** [comment] 2019-07-31 19:35
Well it's not an issue with the SSL implementation. Thanks for the hints :)

**Closed as completed** 2019-07-31 19:35 UTC
Labels: bug
